### ISSUE TITLE
Game Selector spelled wrong everywhere

### ISSUE THREAD

**Issue by Tripleray** [Tripleray/Game-Tool#32]
Game selector is spelled wrong, in some places in application and the html file. Fix spelling and routing with the correct spelling.

**Comment by Tripleray** [comment]
Not sure if everywhere anymore, Just need a double check.

**Comment by LaurenceKelly** [comment]
Fixed few remaining instances where selector was misspelled.

**Comment by Colemayne** [comment]
The last bad "gameselecter" link has been fixed.
