### ISSUE TITLE
Update About page with all Current Contributing Collaborators, and Testers

### ISSUE THREAD

**Issue by Tripleray** [Tripleray/Game-Tool#41]

**Comment by Tripleray** [comment]
Grab pictures of their faces, the more embarrassing the better, in descriptions no personal information, however pictures are fine.

**Comment by Colemayne** [comment]
I can finish this off at some point this weekend.

**Comment by Colemayne** [comment]
Who else should be featured on the about page?

**Comment by Tripleray** [comment]
Anybody who's contributed in the past week or two
